name: wokrflow_name

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "HELLO WORLD!!!!!"

  job_2:
    runs-on: ubuntu-latest
    steps:
      - run: cd ../../ && ls
  
